Spelling: Link, Terminal emulator desc
elementary/terminal pull request #609
Opened 2021-07-15 22:08 UTC by comradekingu

2021-07-19 15:40 UTC, danrabbit requested changes
Thanks for the suggestions! In elementary OS we use the term "secondary click" instead of "right click", because it is device agnostic. Many users are using laptops with multitouch two-finger secondary clicking and for those users the term "right click" doesn't make sense

2021-10-13 15:43 UTC, jeremypw requested changes

2024-08-31 17:27 UTC, jeremypw commented
Closing through lack of progress.

2024-08-31 18:26 UTC, comradekingu commented
@jeremypw Missed this. Helps to ping if things have gone by the wayside.

2024-08-31 19:12 UTC, jeremypw commented
@comradekingu Please re-open if you wish this to be reconsidered.  @danirabbit has some comments that have not been resolved so maybe ping her to discuss.  I guess fixing questionable wording on old release notes may not be a high priority, but there are some valid points to be considered for subsequent releases.

2024-09-07 11:24 UTC, comradekingu commented
@jeremypw I can't reopen it. I am not part of the org.

If you want it can then be reverted to "secondary-click" and that can be an issue for another day.

My thinking is that people having changed clicking over to the other side or use special equipment know about it.
That way mostly everyone else can figure out what side the clicking occurs from its naming.

2024-09-07 11:36 UTC, comradekingu commented
@lenemter Luckily the fixed description is all that is left after conflicts. :)

2024-09-07 11:37 UTC, comradekingu commented on data/io.elementary.terminal.appdata.xml.in
> +    <p>Terminal is a terminal emulator for accessing a UNIX shell environment that can run programs available on your system.</p>
```suggestion
    <p>Terminal is a terminal emulator for accessing a Unix shell environment that can run programs available on your system.</p>
```

2024-09-07 16:15 UTC, danirabbit reviewed
Generally, this isn't a great app description and that's not your fault at all. But I'm hesitant to say that these changes are enough of an improvement to break all the existing translations. Changing "which" to "that" feels like a pretty minor style thing and not really necessary or an improvement.

I would personally be more happy to merge something that was a much better description that would feel more obviously worth requiring all the re-translation. But I also am not gonna object if someone else feels like this is enough of an improvement to merge it

2024-09-07 19:02 UTC, comradekingu commented
@danirabbit 
The translations aren't broken, they are just fuzzified.
I'll have a look to see what I can do.
At least we agree it wasn't at all good :)

2024-11-03 16:21 UTC, jeremypw reviewed
This is better as it uses less jargon.  Google AI gave the following description which is even less technical:
```
... a text-based user interface (UI) that allows users to interact with their computer by entering commands. 
```

2024-11-20 17:51 UTC, jeremypw commented
@comradekingu Would you consider a description similar to the Google AI one?

2026-02-23 15:17 UTC, jeremypw commented
Closing as OP is no longer responding.

2026-02-23 15:17 UTC, closed without merging