#11: Findbar arrow sensitivity
elementary/terminal pull request #687
Opened 2022-09-18 15:29 UTC by hollyschilling

Added changes to the sensitivity of next and previous buttons when no results are found.

2022-09-23 18:24 UTC, jeremypw commented
@hollyschilling The linter is `vala-lint` with the default configuration. You can download and install locally from https://github.com/vala-lang/vala-lint.  You can then check you code locally before committing.

2022-09-23 18:27 UTC, jeremypw commented
Further info on elementary code style, which the linter enforces can be found here: https://docs.elementary.io/develop/writing-apps/code-style

There should probably be info about linting locally there but as yet it has not been added.

2022-09-23 23:10 UTC, hollyschilling commented
I'm sorry to keep bugging you for simple questions, but I'm having an error with the linting that I can't understand. Specifically, I received and error stating: 

```
  117.26    error   Expected variable name in underscore_convention   naming-convention
```

The referenced line of code is `bool initialFound = next_search ();`. I can't understand why this declaration would be preceded with an underscore. For context, the line is in a try block, in a lambda, in the constructor. What is the rule that is triggering this to get that error?

2022-09-24 05:07 UTC, lenemter commented
@hollyschilling in Vala variables are named using snake_case, and `initialFound` should be `initial_found`

2022-09-25 10:57 UTC, jeremypw requested changes
I have suggested some corrections to remaining lint.

2022-09-25 10:57 UTC, jeremypw commented on src/Widgets/SearchToolbar.vala
> +                window.get_simple_action (MainWindow.ACTION_SEARCH_NEXT).set_enabled(  found);
```suggestion
                window.get_simple_action (MainWindow.ACTION_SEARCH_NEXT).set_enabled (found);
```

2022-09-25 10:57 UTC, jeremypw commented on src/Widgets/SearchToolbar.vala
> +                window.get_simple_action (MainWindow.ACTION_SEARCH_NEXT).set_enabled(  true);
```suggestion
                window.get_simple_action (MainWindow.ACTION_SEARCH_NEXT).set_enabled (true);
```

2022-09-25 10:57 UTC, jeremypw commented on src/Widgets/SearchToolbar.vala
> +            return found;
```suggestion

            return found;
```

2022-09-25 10:57 UTC, jeremypw commented on src/Widgets/SearchToolbar.vala
> +                window.get_simple_action (MainWindow.ACTION_SEARCH_PREVIOUS).set_enabled(  found);
```suggestion
                window.get_simple_action (MainWindow.ACTION_SEARCH_PREVIOUS).set_enabled (found);
```

2022-09-25 10:57 UTC, jeremypw commented on src/Widgets/SearchToolbar.vala
> +                window.get_simple_action (MainWindow.ACTION_SEARCH_PREVIOUS).set_enabled(  true);
```suggestion
                window.get_simple_action (MainWindow.ACTION_SEARCH_PREVIOUS).set_enabled (true);
```

2022-09-25 10:57 UTC, jeremypw commented on src/Widgets/SearchToolbar.vala
> +            return found;
```suggestion
            return found;
```
```suggestion

            return found;
```

2022-09-25 11:13 UTC, jeremypw commented
A side-effect of this change is that if, after the search, the terminal produces output containing the search term then the navigation buttons remain insensitive even if the cyclic search button is toggled.  The search term has to be modified or re-entered in order to initiate a new search.  A more convenient way of refreshing the search would be good. At least if the cyclic search button is toggled then the sensitivity of the navigation buttons should be revisited.

2022-09-25 14:22 UTC, hollyschilling commented on src/Widgets/SearchToolbar.vala
> +            return found;
What is this change?

2022-09-25 14:34 UTC, lenemter commented on src/Widgets/SearchToolbar.vala
> +            return found;
A blank line before return

2022-09-25 14:40 UTC, hollyschilling commented
I completely agree that this is potentially undesirable behavior. Is there an event emitted from the terminal that would indicate that additional content has been added? 

There are a few such edge cases that are not handled well. I feel that adding messaging to indicate that the end of search has been reached would be appropriate.

2022-09-25 17:05 UTC, jeremypw commented
> Is there an event emitted from the terminal that would indicate that additional content has been added?

There is `Vte.Terminal.content-changed` signal.  But you may need to throttle that so that a large number of searches are not performed unnecessarily when the content is changing rapidly.  Maybe better leave that for another PR.

2022-09-25 17:26 UTC, jeremypw requested changes
Another small bug is that if cyclic search is OFF and you navigate to the last found term so that the `next` button becomes insensitive and then toggle cyclic search ON then the sensitivity of the `next` button does not change - it should become sensitive.

A fix for this would be to emit a `search-changed` signal whenever the cyclic search is toggled.

2022-09-25 17:26 UTC, jeremypw commented on src/Widgets/SearchToolbar.vala
> +                    if (!initial_found && !cycle_button.active) {
As `initial_found` is only used once we can omit it:
```suggestion
                     /* Search immediately - not after ENTER pressed */
                    if (!next_search () && !cycle_button.active) {
```

2024-10-17 11:13 UTC, jeremypw commented
I looked into completing this but found that because of the way the terminal widget does search one hit at a time (unlike Code which searches for all hits within scope) it is extremely difficult/impossible to set the search arrow sensitivities correctly all the time.  I do not think it is worth spending more time on it tbh.

2024-10-17 11:13 UTC, closed without merging