Expose audible-bell setting in Settings Menu
elementary/terminal pull request #740
Opened 2023-10-21 17:11 UTC by jeremypw

Fixes #596

2023-10-24 19:07 UTC, danirabbit requested changes
Looks good just some minor copy adjustments

2023-10-24 19:07 UTC, danirabbit commented on src/Widgets/SettingsPopover.vala
> +            description = _("Send an event alert for invalid input or multiple possible completions (subject to system sound settings)"),
In the description text in System Settings we say "notify" here. Also use the same format we use in dialogs etc to describe System Settings locations

```suggestion
            description = _("Notify for invalid input or multiple possible completions (subject to System Settings → Sound)"),
```

2023-10-26 09:50 UTC, jeremypw commented
Thanks for the improvements :smile:

2023-10-26 18:17 UTC, danirabbit approved these changes
Looks good :rocket:

2023-10-26 18:17 UTC, merged